### ISSUE TITLE
Basic auto-renting script

### ISSUE THREAD

**Issue by DevonJames** [dloa/alexandria-tradebot#9]
goal should be for a tradebot node to auto-rent miners on miningrigrentals and point their hashes to the alexandria pool so that they could then auto-sell the FLO they win to publishers

Use calculations found here: https://docs.google.com/spreadsheets/d/11uyc3HqaDD4_WfNkgSfGWDb3r5__fR6V4W0CuQb5LmE/edit#gid=0

**Comment by OstlerDev** [comment]
Completed in the following three repositories:
https://github.com/dloa/autominer-api
https://github.com/dloa/autominer-frontend
https://github.com/dloa/miningrigrentals-api
